[project]
name = "dmddl-sqlmodel"
version = "0.1.0"
description = "SQLModel schema generator for Data Model DSL"
readme = "README.md"
requires-python = "==3.11.11"
dependencies = [
    "sqlmodel==0.0.24",
    "pyyaml==6.0.2",
    "pydantic==2.11.7",
]
license = {text = "FSL-1.1-ALv2"}

[project.scripts]
dmddl-sqlmodel = "dmddl_sqlmodel.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
plugins = ["pydantic.mypy"]
namespace_packages = true
explicit_package_bases = true
mypy_path = "."

[[tool.mypy.overrides]]
module = [
    "sqlmodel.*",
    "yaml.*",
]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "types-pyyaml>=6.0.12.20250516",
]
